    - Blank_issues_enabled: True
    - contact_links:
    - Unset_name: New feedback experience
    - Unset_url: https://learn.microsoft.com/office/new-feedback
    - Unset_about: We’re transitioning our feedback experience away from GitHub Issues. For more information, select Open.
